services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: movieyyk
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: yyk6591/movieproject_avengers-backend:latest
    container_name: backend-container
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/movieyyk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8090:8090"

  frontend:
    image: yyk6591/movieproject_avengers-frontend:latest
    container_name: frontend-container
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

  nginx:
    image: yyk6591/movieproject_avengers-nginx:latest
    container_name: nginx-container
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"

volumes:
  mysql_data:
